name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      # 1. Archivar el código fuente
      - name: Archive source code on success
        if: success() # Solo si todas las acciones anteriores son exitosas
        run: |
          echo "All steps completed successfully. Archiving source code..."
          zip -r success-source-code.zip .
          echo "Source code archived in success-source-code.zip"

      # 2. Subir el archivo ZIP como artefacto
      - name: Upload source code as artifact
        if: success() # Solo si todas las acciones anteriores son exitosas
        uses: actions/upload-artifact@v3
        with:
          name: success-source-code
          path: success-source-code.zip
