name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Archive source code on error
        if: failure() # Only if the previous steps failed
        run: |
          echo "Errors detected. Archiving source code..."
          zip -r error-source-code.zip .
          echo "Source code archived in error-source-code.zip"
      - name: Upload source code as artifact
        if: failure() # Only if the previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: error-source-code
          path: error-source-code.zip
