name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Archive ZIP if code is secure
        run: |
          if [ "${{ steps.snyk.outcome }}" == "success" ]; then
            echo "Code is secure. Archiving source code..."
            zip -r security-threats.zip .
            echo "Source code archived as security-threats.zip"
          else
            echo "Security issues detected. Skipping archiving."
            exit 1
          fi

