name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      # 1. Verificar que el código es seguro
      - name: Verify security scan results
        id: verify_scan
        run: |
          if grep -q "error" snyk.sarif; then
            echo "Security issues detected. Failing the workflow."
            exit 0
          else
            echo "No security issues detected. Proceeding with archiving."
          fi

      # 2. Archivar el código fuente si es seguro
      - name: Archive source code
        if: success() # Solo si no se detectaron vulnerabilidades
        run: |
          echo "Archiving source code..."
          zip -r secure-source-code.zip .
          echo "Source code archived in secure-source-code.zip"

      # 3. Subir el archivo ZIP como artefacto
      - name: Upload source code as artifact
        if: success() # Solo si no se detectaron vulnerabilidades
        uses: actions/upload-artifact@v3
        with:
          name: secure-source-code
          path: secure-source-code.zip
